image_formats:
  - bmp
  - gif
  - heic
  - jpeg
  - jpg
  - m4v
  - png
  - raf
  - tif
  - tiff
  - wmv
  # non-pixel-streamable
  - aae
  - avi
  - mov
  - mp4
  - mpeg
  - mpg
  - psd
  - raw
  - wav
  - xmp

known_formats:
  - timestamp
  - toml
  - o
  - rmeta
  - iml
  - sample
  - rs
  - bin

skip_dirs:
  - System
  - Users
  - etc
  - private
  - usr
  - no_index
  - .Trashes
